server:
  port: 9712
spring:
  application:
    name: complifybook
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=t1001
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5 # Maximum number of connections in the pool
      minimum-idle: 1      # Minimum number of idle connections in the pool
      max-lifetime: 900000 # 15 minutes (in milliseconds)
      idle-timeout: 300000 # 5 minutes (in milliseconds)

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: abhaempire@gmail.com
#    password: cvlh jnlj ilvy koxx
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

# Actuator for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    metrics:
      enabled: true
  metrics:
    tags:
      application: complifybook

providermap:
  providerConfig:
    activeSmsProvider: WAY2SMS